---
name: Validate HACS
on:
  push:
  pull_request:
jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
